version: '2.2'

services:
  app:
    image: l8518/thesis-predictionio-basic-recommender:1.3
    container_name: basic-recommender # Required by EFARS for monitoring
    volumes:
    - ./:/home/pio/app/src
    - ~/.ssh:/home/pio/.ssh
    ports:
    - 9000:9000
    - 8000:8000
    - 7070:7070
    environment:
      PIO_STORAGE_SOURCES_PGSQL_TYPE: jdbc
      PIO_STORAGE_SOURCES_PGSQL_URL: "jdbc:postgresql://postgres/pio"
      PIO_STORAGE_SOURCES_PGSQL_USERNAME: pio
      PIO_STORAGE_SOURCES_PGSQL_PASSWORD: pio
      PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME: pio_event
      PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE: PGSQL
      PIO_STORAGE_REPOSITORIES_METADATA_NAME: pio_meta
      PIO_STORAGE_REPOSITORIES_METADATA_SOURCE: PGSQL
      PIO_STORAGE_REPOSITORIES_MODELDATA_NAME: pio_model
      PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE: PGSQL
      BASIC_REC_WARM_UP_DELAY: 30
      BASIC_REC_DRIVER_MEM: 64G
      BASIC_REC_EXECUTOR_MEM: 64G
      BASIC_REC_TRAIN_DEPLOY_STEPS_SKIPPED: 10
  postgres:
    image: postgres:9.6.12
    container_name: database # Required by EFARS for monitoring
    environment:
      POSTGRES_USER: pio
      POSTGRES_PASSWORD: pio
      POSTGRES_DB: pio
      POSTGRES_INITDB_ARGS: --encoding=UTF8